version: '3'
services:
    duplicati:
        image: ghcr.io/linuxserver/duplicati:latest
        container_name: duplicati
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${MEDIABOX_PATH}/duplicati:/config
            - ${MEDIABOX_PATH}/duplicati/backups:/backups
            - ${MEDIABOX_PATH}:/source
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8200:8200
        restart: unless-stopped
        networks:
            - mediabox_network

    sabnzbd:
        image: ghcr.io/linuxserver/sabnzbd:latest
        container_name: sabnzbd
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${MEDIABOX_PATH}/sabnzbd:/config
            - /media/HDD/downloads:/downloads
            - /media/HDD/incomplete-downloads:/incomplete-downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8081:8080
        restart: unless-stopped
        networks:
            - mediabox_network

    sonarr:
        image: ghcr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${MEDIABOX_PATH}/sonarr:/config
            - /media/HDD/Media/tv_shows:/tv
            - /media/HDD/downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8989:8989
        restart: unless-stopped
        networks:
            - mediabox_network

    radarr:
        image: ghcr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${MEDIABOX_PATH}/radarr:/config
            - /media/HDD/Media/movies:/movies
            - /media/HDD/downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 7878:7878
        restart: unless-stopped
        networks:
            - mediabox_network

    bazarr:
        image: ghcr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${MEDIABOX_PATH}/bazarr:/config
            - /media/HDD/Media/movies:/movies
            - /media/HDD/Media/tv_shows:/tv
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 6767:6767
        restart: unless-stopped
        networks:
            - mediabox_network

    overseerr:
        image: ghcr.io/linuxserver/overseerr:latest
        container_name: overseerr
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${MEDIABOX_PATH}/overseerr:/config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5055:5055
        restart: unless-stopped
        networks:
            - mediabox_network

    plex:
        image: ghcr.io/linuxserver/plex:1.25.4
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
            - PLEX_CLAIM=claim-W5WTiks9n28nFUrXmiFx
        volumes:
            - ${MEDIABOX_PATH}/plex:/config
            - /media/HDD/Media/tv_shows:/tv
            - /media/HDD/Media/movies:/movies
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5055:5055
        restart: unless-stopped

    homeassistant:
        container_name: homeassistant
        image: "ghcr.io/home-assistant/home-assistant:stable"
        volumes:
            - ${MEDIABOX_PATH}/homeassistant:/config
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
        privileged: true
        network_mode: host

    glances:
        image: nicolargo/glances:latest-alpine
        container_name: glances
        restart: unless-stopped
        pid: host
        ports:
            - '61208:61208'
        environment:
            - PUID=1000
            - PGID=1000
            - GLANCES_OPT=-w
        volumes:
            - ${MEDIABOX_PATH}/glances:/config
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - mediabox_network

    muximux:
        image: lscr.io/linuxserver/muximux
        container_name: muximux
        restart: unless-stopped
        ports:
            - '8087:80'
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${MEDIABOX_PATH}/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        networks:
            - mediabox_network

    duckdns:
        image: lscr.io/linuxserver/duckdns:latest
        container_name: duckdns
        environment:
            - PUID=1000
            - PGID=1000
            - SUBDOMAINS=capzulu
            - TOKEN=e87b360a-cabc-41c9-84b4-bc87f96cc850
            - LOG_FILE=false
        volumes:
            - ${MEDIABOX_PATH}/duckdns/config:/config
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
        networks:
            - mediabox_network

    swag:
        image: lscr.io/linuxserver/swag
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - URL=capzulu.duckdns.org
            - VALIDATION=duckdns
            - SUBDOMAINS=wildcard
            - DUCKDNSTOKEN=e87b360a-cabc-41c9-84b4-bc87f96cc850
        volumes:
            - ${MEDIABOX_PATH}/swag:/config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 443:443
        networks:
            - mediabox_network
        restart: unless-stopped

    deluge:
        image: lscr.io/linuxserver/deluge:latest
        container_name: deluge
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${MEDIABOX_PATH}/deluge:/config
            - /media/HDD/downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8112:8112
            - 6881:6881
            - 6881:6881/udp
        restart: unless-stopped
        networks:
            - mediabox_network

    prowlarr:
        image: lscr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${MEDIABOX_PATH}/prowlarr:/config
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 9696:9696
        restart: unless-stopped
        networks:
            - mediabox_network

    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        ports:
            - "8191:8191"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
        networks:
            - mediabox_network

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        networks:
            - mediabox_network

    nginx-proxy-manager:
        image: jlesage/nginx-proxy-manager:latest
        container_name: nginx-proxy-manager
        ports:
            - "8181:8181"
            - "8080:8080"
            - "4443:4443"
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${MEDIABOX_PATH}/nginx-proxy-manager:/config:rw"
        restart: unless-stopped
        networks:
            - mediabox_network

networks:
  mediabox_network:
    name: mediabox
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv6: "false"
    ipam:
     config:
       - subnet: 172.23.0.0/16
         gateway: 172.23.0.1
