---
- name: Deploy HomeServeMate
  hosts: all
  tasks:
    - name: Install dependencies
      include_role:
        name: dependencies

    - name: Install mergerfs and configure mounts
      include_role:
        name: mergerfs

    - name: Install k3s
      include_role:
        name: k3s

    - name: Install cert-manager
      include_role:
        name: cert-manager

    - name: Install cloudflared
      include_role:
        name: cloudflared
      when: install_cloudflared

    - name: Install adguard-home
      include_role:
        name: adguard-home
      when: install_adguard_home

    - name: Install services
      include_role:
        name: services
