---
- name: Deploy HomeServeMate
  hosts: all
  tasks:
    - name: Install dependencies
      include_role:
        name: dependencies

    - name: Install mergerfs and configure mounts
      include_role:
        name: mergerfs

    - name: Install k3s
      include_role:
        name: k3s

    - name: Install cert-manager
      include_role:
        name: cert-manager

    - name: Install cloudflared
      include_role:
        name: cloudflared
      when: install_cloudflared

    - name: Install adguard-home
      include_role:
        name: adguard-home
      when: install_adguard_home

    - name: Install services
      include_role:
        name: services

    # - include_tasks: helm.yml

    

    # - name: Copy cloudflare_secret.yml to remote server
    #   copy:
    #     src: cloudflare_secret.yml
    #     dest: /tmp/cloudflare_secret.yml

    # - name: Apply cloudflare_secret manifest to the cluster.
    #   kubernetes.core.k8s:
    #     state: present
    #     src: /tmp/cloudflare_secret.yml

    # - name: Delete cloudflare_secret.yml file
    #   file:
    #     state: absent
    #     path: /tmp/cloudflare_secret.yml

    # - name: Copy cluster-issuer.yml to remote server
    #   copy:
    #     src: cluster-issuer.yml
    #     dest: /tmp/cluster-issuer.yml

    # - name: Apply cluster-issuer manifest to the cluster.
    #   kubernetes.core.k8s:
    #     state: present
    #     src: /tmp/cluster-issuer.yml

    # - name: Delete cluster-issuer.yml file
    #   file:
    #     state: absent
    #     path: /tmp/cluster-issuer.yml
