version: '3.5'

services:
  sabnzbd:
    image: 'ghcr.io/linuxserver/sabnzbd:4.0.3'
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - '${DATA_PATH}/sabnzbd:/config'
      - '${DATA_PATH}/downloads/complete:/downloads'
      - '${DATA_PATH}/downloads/incomplete:/incomplete-downloads'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '8081:8080'
    restart: unless-stopped
    networks:
      - media

  sonarr:
    image: 'ghcr.io/linuxserver/sonarr:3.0.10'
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - '${DATA_PATH}/sonarr:/config'
      - '/media/HDD/Media/tv_shows:/tv'
      - '${DATA_PATH}/downloads/converted:/downloads'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '8989:8989'
    restart: unless-stopped
    networks:
      - media

  radarr:
    image: 'ghcr.io/linuxserver/radarr:4.7.5'
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - '${DATA_PATH}/radarr:/config'
      - '/media/HDD/Media/movies:/movies'
      - '${DATA_PATH}/downloads/converted:/downloads'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '7878:7878'
    restart: unless-stopped
    networks:
      - media

  bazarr:
    image: 'ghcr.io/linuxserver/bazarr:1.3.0'
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - '6767:6767'
    volumes:
      - '${DATA_PATH}/bazarr:/config'
      - '/media/HDD/Media/movies:/movies'
      - '/media/HDD/Media/tv_shows:/tv'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    networks:
      - media

  #overseerr:
  #  image: 'ghcr.io/linuxserver/overseerr:1.33.2'
  #  container_name: overseerr
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #  volumes:
  #    - '${DATA_PATH}/overseerr:/config'
  #    - '/etc/localtime:/etc/localtime:ro'
  #  ports:
  #    - '5055:5055'
  #  restart: unless-stopped
  #  networks:
  #    - media

  jellyseerr:
    image: fallenbagel/jellyseerr:1.7.0
    container_name: jellyseerr
    environment:
      - 'TZ=${TIMEZONE}'
    ports:
      - 5055:5055
    volumes:
     - '${DATA_PATH}/jellyseerr:/app/config'
    restart: unless-stopped
    networks:
      - media

  #plex:
  #  image: 'ghcr.io/linuxserver/plex:1.32.5'
  #  container_name: plex
  #  network_mode: host
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - VERSION=docker
  #    - PLEX_CLAIM=claim-W5WTiks9n28nFUrXmiFx
  #  volumes:
  #    - '${DATA_PATH}/plex:/config'
  #    - '/media/HDD/Media/tv_shows:/tv'
  #    - '/media/HDD/Media/movies:/movies'
  #    - '/etc/localtime:/etc/localtime:ro'
  #  restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.8.10
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - 'TZ=${TIMEZONE}'
    volumes:
      - '${DATA_PATH}/jellyfin:/config'
      - '/media/HDD/Media/tv_shows:/data/tvshows'
      - '/media/HDD/Media/movies:/data/movies'
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1901:1900/udp
    restart: unless-stopped
    networks:
      - media

  deluge:
    image: 'lscr.io/linuxserver/deluge:2.1.1'
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - '${DATA_PATH}/deluge:/config'
      - '/media/HDD/downloads/complete:/downloads'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '8112:8112'
      - '6881:6881'
      - '6881:6881/udp'
    restart: unless-stopped
    networks:
      - media

  prowlarr:
    image: 'lscr.io/linuxserver/prowlarr:1.8.6'
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - '${DATA_PATH}/prowlarr:/config'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '9696:9696'
    restart: unless-stopped
    networks:
      - media

  flaresolverr:
    image: 'ghcr.io/flaresolverr/flaresolverr:v3.3.6'
    container_name: flaresolverr
    ports:
      - '8191:8191'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    networks:
      - media

  fileflows:
    image: revenz/fileflows:23.09
    container_name: fileflows
    environment:
      - 'TZ=${TIMEZONE}'
      - TempPathHost=/tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - '${DATA_PATH}/fileflows/data:/app/Data'
      - '${DATA_PATH}/fileflows/logs:/app/Logs'
      - /tmp:/tmp
      - '${DATA_PATH}/downloads:/media'
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - media


networks:
  media:
    name: media
    driver: bridge
