---
collections:
  - name: community.kubernetes
    version: 2.0.1
  - name: ansible.utils
    version: 2.11.0
  - name: kubernetes.core
    version: 3.0.1
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s
    version: v3.4.4