---
all:
  hosts:
    <target IP address>:
      ansible_ssh_user: <username>
  vars:
    # General
    domain: internet domain
    email: email for letsencrypt
    timezone: timezone, ex. Europe/Amsterdam
    data_path: /opt/HomeServeMate
    media_path: path to media storage
    # Adguard-Home
    install_adguard_home: true
    adguard_home_username: adguard home username
    adguard_home_password: adguard home password
    adguard_home_user_rules:
      - dns resolution similar to /etc/hosts in the form of <ip_address dns>
    # Cloudflare
    install_cloudflared: true
    cloudflare_api_token: cloudflare api token
    cloudflare_tunnel_name: cloudflared tunnel name
    cloudflare_tunnel_dns_list: # list here the services deployed on k3s that you want to expose to the internet
      - name: dns name of the service
        port: port of the service
    cloudflared_pem: |-
      paste here your cloudflared pem file content
    # Tailscale
    tailscale_auth_key: tailscale auth key
    # Services
    zigbee_adapter_path: specify the connection to zigbee adapter
    enable_services:
      - duplicati
      - homeassistant
      - homer
      - mqtt
      - tailscale
      - unifi-controller
      - uptimekuma
      - zigbee2mqtt
      - bazarr
      - deluge
      - flaresolverr
      - prowlarr
      - radarr
      - sabnzbd
      - sonarr
      - jellyfin
      - jellyseerr
      - recyclarr
    services_not_shown_on_homer: ["homer", "flaresolverr", "mqtt", "recyclarr"]