---
- name: Copy mosquitto.conf to folder
  ansible.builtin.copy:
    src: mosquitto.conf
    dest: "{{ mediabox_data_path}}/mqtt/mosquitto.conf"

- name: Get all *.yml.j2 files
  delegate_to: localhost
  ansible.builtin.find:
    paths: "{{ role_path }}/templates"
    patterns: "*.yml.j2"
  register: template_files
  changed_when: false

- name: Process template files
  block:
    - name: Copy template files
      ansible.builtin.template:
        src: "{{ item.path }}"
        dest: "/tmp/{{ item.path | basename | replace('.j2', '') }}"
      loop: "{{ template_files.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Deploy apps
      shell: |
        casaos-cli app-management install -f /tmp/{{ item.path | basename | replace('.j2', '') }}
      loop: "{{ template_files.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Delete template files
      ansible.builtin.file:
        path: "/tmp/{{ item.path | basename | replace('.j2', '') }}"
        state: absent
      loop: "{{ template_files.files }}"
      loop_control:
        label: "{{ item.path }}"
  when: template_files.matched > 0
