---
- name: Download and install mergerfs
  get_url:
    url: "{{ mergerfs_binary }}"
    dest: "/tmp/mergerfs.deb"

- name: Install mergerfs package
  apt:
    deb: "/tmp/mergerfs.deb"

- name: Delete mergerfs package
  file:
    path: /tmp/mergerfs.deb
    state: absent

- name: Create mount points
  file:
    path: "/media/{{ item }}"
    state: directory
  loop: "{{ diskpool_parts }}"

- name: Get UUIDs of partitions
  become: true
  command: "blkid -s UUID -o value /dev/{{ item }}"
  loop: "{{ diskpool_parts }}"
  register: blkid_output
  changed_when: false

- name: Add comments to fstab for diskpool
  become: true
  lineinfile:
    path: /etc/fstab
    line: "# disk pool"
    insertafter: EOF

- name: Add entries to fstab for each partition
  become: true
  mount:
    path: "/media/{{ item.item }}"
    src: "UUID={{ item.stdout }}"
    fstype: ext4
    opts: defaults
    state: mounted
    dump: 0
    passno: 0
  loop: "{{ blkid_output.results }}"

- name: Create folder for mergerfs
  file:
    path: "{{ storage_path }}"
    state: directory

- name: Add comments to fstab for diskpool
  become: true
  lineinfile:
    path: /etc/fstab
    line: "# mergerfs"
    insertafter: EOF

- name: Add entries to fstab for each partition
  become: true
  mount:
    path: "{{ storage_path }}"
    src: "{{ diskpool_parts | map('regex_replace', '(.+)', '/media/\\1') | join(':') }}"
    fstype: fuse.mergerfs
    opts: cache.files=partial,dropcacheonclose=true,category.create=mfs,fsname=mergerfs,defaults
    state: mounted
    dump: 0
    passno: 0
