---
- name: "Create {{ data_path }} directory"
  become: true
  ansible.builtin.file:
    path: "{{ data_path }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Install Kubernetes
  ansible.builtin.include_role:
    name: xanmanning.k3s
    public: true
  vars:
    k3s_become: true
    k3s_state: installed
    k3s_release_version: v1.29.4+k3s1

- name: "Create ~/.kube directory"
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "~/.kube"
    state: directory

- name: Copy kubeconfig to the project directory
  become: true
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "~/.kube/config"
    flat: true

- name: Update kubeconfig with the correct load balancer address
  delegate_to: localhost
  run_once: true
  ansible.builtin.replace:
    path: "~/.kube/config"
    regexp: https://127.0.0.1:6443
    replace: "https://{{ ansible_host }}:6443"