---
- name: Install Helm
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

- name: Check if Helm is installed
  command: helm version
  changed_when: false

- name: Install helm-diff
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present

- name: Deploy Actions Runner Controller
  kubernetes.core.helm:
    name: arc
    chart_ref: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    release_namespace: arc-systems
    create_namespace: true

- name: Deploy Runner Scale Set
  shell: "helm upgrade --install arc-runner-set --namespace arc-runners --create-namespace --set githubConfigUrl={{ github_repo }} --set githubConfigSecret.github_token={{ github_personal_access_token }} oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set"

- name: Check if Actions Runner Controller is deployed
  kubernetes.core.helm_info:
    release_namespace: arc-systems
    release_name: arc
  register: helm_release

- name: Fail if Actions Runner Controller is not deployed
  fail:
    msg: "Actions Runner Controller is not deployed"
  when: not helm_release.status

- name: Check if Runner Scale Set is deployed
  kubernetes.core.helm_info:
    release_namespace: arc-runners
    release_name: arc-runner-set
  register: helm_release

- name: Fail if Runner Scale Set is not deployed
  fail:
    msg: "Runner Scale Set is not deployed"
  when: not helm_release.status
