---
- name: Configure AdGuard Home
  hosts: adguard
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:

    - name: Gather facts for the first time
      setup:
    
    - name: Ensure AdGuard Home is installed
      ansible.builtin.stat:
        path: /opt/AdGuardHome/AdGuardHome
      register: adguard_installed
      failed_when: false  # To ensure playbook doesn't fail if file doesn't exist

    - name: Install AdGuard Home if not installed
      include_role:
        name: adguard-home
      when: not adguard_installed.stat.exists
