---
- name: Add extra disk to mediabox
  hosts: pve
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Add disk
      shell: |
        qm set 101 -scsi1 /dev/disk/by-id/wwn-0x5000c500b604c053,backup=0

- name: Configure mediabox
  hosts: mediabox
  gather_facts: no
  any_errors_fatal: true
  vars_files:
    - ./tf_ansible_vars.yml
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:

    - name: Gather facts for the first time
      setup:

    - name: Install dependencies
      include_role:
        name: dependencies

    - name: Set up and mount disk
      become: true
      block:
        - name: Create mount directory
          file:
            path: /mnt/HDD
            state: directory

        - name: Mount disk
          mount:
            path: /mnt/HDD
            src: /dev/sdb1
            fstype: ext4
            state: mounted

    - name: Cloudflared
      include_role:
        name: cloudflared

    - name: CasaOS
      include_role:
        name: casaos

    - name: Apps
      include_role:
        name: apps
