---
- name: Create manifest folder
  ansible.builtin.file:
    path: "{{ data_path }}/manifests"
    state: directory

- name: Download cert-manager manifest
  ansible.builtin.get_url:
    url: https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
    dest: "{{ data_path }}/manifests/cert-manager.yml"
  register: result

- name: Apply cert-manager manifest to the cluster.
  shell: "KUBECONFIG=/home/{{ ansible_user }}/.kube/config kubectl apply -f {{ data_path }}/manifests/cert-manager.yml"
  when: result.changed

- name: Check containers status
  shell: "KUBECONFIG=/home/{{ ansible_user }}/.kube/config kubectl wait pod --for condition=ready --field-selector=status.phase!=Succeeded -n cert-manager --all --timeout 10m"
  changed_when: false
  when: result.changed

- name: Template secret
  ansible.builtin.template:
    src: secret.yml.j2
    dest: "/tmp/secret.yml"

- name: Deploy secret
  shell: "KUBECONFIG=/home/{{ ansible_user }}/.kube/config kubectl apply -f /tmp/secret.yml"

- name: Delete secret template
  ansible.builtin.file:
    path: "/tmp/secret.yml"
    state: absent

- name: Template ClusterIssuer
  ansible.builtin.template:
    src: cluster_issuer.yml.j2
    dest: "/tmp/cluster_issuer.yml"

- name: Deploy ClusterIssuer
  shell: "KUBECONFIG=/home/{{ ansible_user }}/.kube/config kubectl apply -f /tmp/cluster_issuer.yml"

- name: Delete ClusterIssuer template
  ansible.builtin.file:
    path: "/tmp/cluster_issuer.yml"
    state: absent