---
- name: Create manifest folder
  ansible.builtin.file:
    path: "{{ data_path }}/manifests"
    state: directory

- name: Download cert-manager manifest
  ansible.builtin.get_url:
    url: https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
    dest: "{{ data_path }}/manifests/cert-manager.yml"
  register: result

- name: Apply cert-manager manifest to the cluster.
  kubernetes.core.k8s:
    src: "{{ data_path }}/manifests/cert-manager.yml"
    apply: true
    server_side_apply:
      field_manager: ansible
  when: result.changed

- name: Check containers status
  shell: "KUBECONFIG=/home/{{ ansible_user }}/.kube/config kubectl wait pod --for condition=ready --field-selector=status.phase!=Succeeded -n cert-manager --all --timeout 10m"
  changed_when: false
  when: result.changed

- name: Deploy secret
  kubernetes.core.k8s:
    template: "secret.yml.j2"
    apply: true
    server_side_apply:
      field_manager: ansible

- name: Deploy ClusterIssuer
  kubernetes.core.k8s:
    template: "cluster_issuer.yml.j2"
    apply: true
    server_side_apply:
      field_manager: ansible