---
- name: Create manifest folder
  ansible.builtin.file:
    path: "{{ data_path }}/manifests"
    state: directory

- name: Apply cert-manager manifest
  shell: "KUBECONFIG=/home/{{ ansible_user }}/.kube/config kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.yaml"
  register: result

- name: Download and install cmctl
  shell: |
    curl -fsSL -o cmctl https://github.com/cert-manager/cmctl/releases/download/{{ cmctl_version }}/cmctl_linux_arm64
    chmod +x cmctl
    sudo mv cmctl /usr/local/bin

- name: cmcyl dry-run
  shell: "cmctl check api --wait=2m"

- name: Check containers status
  shell: "KUBECONFIG=/home/{{ ansible_user }}/.kube/config kubectl wait pod --for condition=ready --field-selector=status.phase!=Succeeded -n cert-manager --all --timeout 10m"
  changed_when: false
  when: result.changed

- name: Template secret
  ansible.builtin.template:
    src: secret.yml.j2
    dest: "/tmp/secret.yml"

- name: Deploy secret
  shell: "KUBECONFIG=/home/{{ ansible_user }}/.kube/config kubectl apply -f /tmp/secret.yml"

- name: Delete secret template
  ansible.builtin.file:
    path: "/tmp/secret.yml"
    state: absent

- name: Template ClusterIssuer
  ansible.builtin.template:
    src: cluster_issuer.yml.j2
    dest: "/tmp/cluster_issuer.yml"

- name: Deploy ClusterIssuer
  shell: "KUBECONFIG=/home/{{ ansible_user }}/.kube/config kubectl apply -f /tmp/cluster_issuer.yml"

- name: Delete ClusterIssuer template
  ansible.builtin.file:
    path: "/tmp/cluster_issuer.yml"
    state: absent