---
- name: Add Authentik chart repo
  kubernetes.core.helm_repository:
    name: authentik
    repo_url: "https://charts.goauthentik.io"

- name: Deploy Authentik chart
  kubernetes.core.helm:
    name: authentik
    chart_ref: authentik/authentik
    release_namespace: infra
    create_namespace: true
    values: "{{ lookup('template', 'values.yml.j2') | from_yaml }}"
    update_repo_cache: true
    force: true
