---
- name: Update APT package cache
  become: true
  apt:
    update_cache: true

- name: Upgrade all packages
  become: true
  apt:
    upgrade: true

- name: Install required dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Install kubernetes Python library
  become: true
  pip:
    name: kubernetes

- name: Check if a reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if required
  become: true
  reboot:
    msg: "Rebooting the system as updates require it"
  when: reboot_required.stat.exists
  async: "{{ reboot_timeout }}"  # Set a reasonable timeout for the reboot to complete
  poll: 0     # Don't wait for the reboot to complete

- name: Wait for the system to come back online
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
  when: reboot_required.stat.exists