---
name: Ansible lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  lint:
    runs-on: arc-runner-set

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install YAML Lint
        run: |
          pip install yamllint

      - name: Lint YAML files
        run: yamllint .
