name: Deploy HomeServeMate

on:
  schedule:
    - cron: '0 8 * * 1'  # This schedules the workflow to run at 08:00 every Monday
  workflow_dispatch:

jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Test
        run: |
          uname -A

      - name: test 2
        run: |
          cat /etc/os-release
            
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: install.yml
          requirements: requirements.yml
          options: |
            --inventory inventory/inventory.yml
