name: Deploy HomeServeMate

on:
  schedule:
    - cron: '0 8 * * 1'  # This schedules the workflow to run at 08:00 every Monday
  workflow_dispatch:

jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: install.yml
          directory: ./HomeServeMate/.
          options: |
            --inventory inventory/inventory.yml
